grails-app/domain/com/kathsoftware/SecAppUser.groovy
package com.kathsoftware

class SecAppUser {

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<SecAppRole> getAuthorities() {
		SecAppUserSecAppRole.findAllBySecAppUser(this).collect { it.secAppRole }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}

grails-app/controllers/com/kathsoftware/SecAppUserController.groovy
package com.kathsoftware

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import grails.converters.JSON


@Transactional(readOnly = true)
class SecAppUserController {

    static allowedMethods = [getUserList: "GET", create: "GET", save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond SecAppUser.list(params), model:[secAppUserInstanceCount: SecAppUser.count()]
    }

    def show(SecAppUser secAppUserInstance) {
        respond secAppUserInstance
    }

    def create() {
        respond new SecAppUser(params)
    }

    @Transactional
    def save(SecAppUser secAppUserInstance) {
        if (secAppUserInstance == null) {
            notFound()
            return
        }

        if (secAppUserInstance.hasErrors()) {
            respond secAppUserInstance.errors, view:'create'
            return
        }

        secAppUserInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'secAppUser.label', default: 'SecAppUser'), secAppUserInstance.id])
                redirect secAppUserInstance
            }
            '*' { respond secAppUserInstance, [status: CREATED] }
        }
    }

    def edit(SecAppUser secAppUserInstance) {
        respond secAppUserInstance
    }

    @Transactional
    def update(SecAppUser secAppUserInstance) {
        if (secAppUserInstance == null) {
            notFound()
            return
        }

        if (secAppUserInstance.hasErrors()) {
            respond secAppUserInstance.errors, view:'edit'
            return
        }

        secAppUserInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'SecAppUser.label', default: 'SecAppUser'), secAppUserInstance.id])
                redirect secAppUserInstance
            }
            '*'{ respond secAppUserInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(SecAppUser secAppUserInstance) {

        if (secAppUserInstance == null) {
            notFound()
            return
        }

        secAppUserInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'SecAppUser.label', default: 'SecAppUser'), secAppUserInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'secAppUser.label', default: 'SecAppUser'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/secAppUser/_form.gsp
<%@ page import="com.kathsoftware.SecAppUser" %>



<div class="fieldcontain ${hasErrors(bean: secAppUserInstance, field: 'username', 'error')} required">
	<label for="username">
		<g:message code="secAppUser.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="username" required="" value="${secAppUserInstance?.username}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: secAppUserInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="secAppUser.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="password" required="" value="${secAppUserInstance?.password}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: secAppUserInstance, field: 'accountExpired', 'error')} ">
	<label for="accountExpired">
		<g:message code="secAppUser.accountExpired.label" default="Account Expired" />
		
	</label>
	<g:checkBox name="accountExpired" value="${secAppUserInstance?.accountExpired}" />

</div>

<div class="fieldcontain ${hasErrors(bean: secAppUserInstance, field: 'accountLocked', 'error')} ">
	<label for="accountLocked">
		<g:message code="secAppUser.accountLocked.label" default="Account Locked" />
		
	</label>
	<g:checkBox name="accountLocked" value="${secAppUserInstance?.accountLocked}" />

</div>

<div class="fieldcontain ${hasErrors(bean: secAppUserInstance, field: 'enabled', 'error')} ">
	<label for="enabled">
		<g:message code="secAppUser.enabled.label" default="Enabled" />
		
	</label>
	<g:checkBox name="enabled" value="${secAppUserInstance?.enabled}" />

</div>

<div class="fieldcontain ${hasErrors(bean: secAppUserInstance, field: 'passwordExpired', 'error')} ">
	<label for="passwordExpired">
		<g:message code="secAppUser.passwordExpired.label" default="Password Expired" />
		
	</label>
	<g:checkBox name="passwordExpired" value="${secAppUserInstance?.passwordExpired}" />

</div>

grails-app/views/secAppUser/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUser.label', default: 'SecAppUser')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-secAppUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-secAppUser" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${secAppUserInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${secAppUserInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:secAppUserInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/secAppUser/edit.gsp
<%@ page import="com.kathsoftware.SecAppUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUser.label', default: 'SecAppUser')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-secAppUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-secAppUser" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${secAppUserInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${secAppUserInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:secAppUserInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${secAppUserInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/secAppUser/index.gsp
<%@ page import="com.kathsoftware.SecAppUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUser.label', default: 'SecAppUser')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-secAppUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-secAppUser" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="username" title="${message(code: 'secAppUser.username.label', default: 'Username')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'secAppUser.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="accountExpired" title="${message(code: 'secAppUser.accountExpired.label', default: 'Account Expired')}" />
					
						<g:sortableColumn property="accountLocked" title="${message(code: 'secAppUser.accountLocked.label', default: 'Account Locked')}" />
					
						<g:sortableColumn property="enabled" title="${message(code: 'secAppUser.enabled.label', default: 'Enabled')}" />
					
						<g:sortableColumn property="passwordExpired" title="${message(code: 'secAppUser.passwordExpired.label', default: 'Password Expired')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${secAppUserInstanceList}" status="i" var="secAppUserInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${secAppUserInstance.id}">${fieldValue(bean: secAppUserInstance, field: "username")}</g:link></td>
					
						<td>${fieldValue(bean: secAppUserInstance, field: "password")}</td>
					
						<td><g:formatBoolean boolean="${secAppUserInstance.accountExpired}" /></td>
					
						<td><g:formatBoolean boolean="${secAppUserInstance.accountLocked}" /></td>
					
						<td><g:formatBoolean boolean="${secAppUserInstance.enabled}" /></td>
					
						<td><g:formatBoolean boolean="${secAppUserInstance.passwordExpired}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${secAppUserInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/secAppUser/show.gsp
<%@ page import="com.kathsoftware.SecAppUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUser.label', default: 'SecAppUser')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-secAppUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-secAppUser" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list secAppUser">
			
				<g:if test="${secAppUserInstance?.username}">
				<li class="fieldcontain">
					<span id="username-label" class="property-label"><g:message code="secAppUser.username.label" default="Username" /></span>
					
						<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${secAppUserInstance}" field="username"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${secAppUserInstance?.password}">
				<li class="fieldcontain">
					<span id="password-label" class="property-label"><g:message code="secAppUser.password.label" default="Password" /></span>
					
						<span class="property-value" aria-labelledby="password-label"><g:fieldValue bean="${secAppUserInstance}" field="password"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${secAppUserInstance?.accountExpired}">
				<li class="fieldcontain">
					<span id="accountExpired-label" class="property-label"><g:message code="secAppUser.accountExpired.label" default="Account Expired" /></span>
					
						<span class="property-value" aria-labelledby="accountExpired-label"><g:formatBoolean boolean="${secAppUserInstance?.accountExpired}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${secAppUserInstance?.accountLocked}">
				<li class="fieldcontain">
					<span id="accountLocked-label" class="property-label"><g:message code="secAppUser.accountLocked.label" default="Account Locked" /></span>
					
						<span class="property-value" aria-labelledby="accountLocked-label"><g:formatBoolean boolean="${secAppUserInstance?.accountLocked}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${secAppUserInstance?.enabled}">
				<li class="fieldcontain">
					<span id="enabled-label" class="property-label"><g:message code="secAppUser.enabled.label" default="Enabled" /></span>
					
						<span class="property-value" aria-labelledby="enabled-label"><g:formatBoolean boolean="${secAppUserInstance?.enabled}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${secAppUserInstance?.passwordExpired}">
				<li class="fieldcontain">
					<span id="passwordExpired-label" class="property-label"><g:message code="secAppUser.passwordExpired.label" default="Password Expired" /></span>
					
						<span class="property-value" aria-labelledby="passwordExpired-label"><g:formatBoolean boolean="${secAppUserInstance?.passwordExpired}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:secAppUserInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${secAppUserInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>