grails-app/domain/com/kathsoftware/SecAppUserSecAppRole.groovy
package com.kathsoftware

import org.apache.commons.lang.builder.HashCodeBuilder

class SecAppUserSecAppRole implements Serializable {

	private static final long serialVersionUID = 1

	SecAppUser secAppUser
	SecAppRole secAppRole

	boolean equals(other) {
		if (!(other instanceof SecAppUserSecAppRole)) {
			return false
		}

		other.secAppUser?.id == secAppUser?.id &&
		other.secAppRole?.id == secAppRole?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (secAppUser) builder.append(secAppUser.id)
		if (secAppRole) builder.append(secAppRole.id)
		builder.toHashCode()
	}

	static SecAppUserSecAppRole get(long secAppUserId, long secAppRoleId) {
		SecAppUserSecAppRole.where {
			secAppUser == SecAppUser.load(secAppUserId) &&
			secAppRole == SecAppRole.load(secAppRoleId)
		}.get()
	}

	static boolean exists(long secAppUserId, long secAppRoleId) {
		SecAppUserSecAppRole.where {
			secAppUser == SecAppUser.load(secAppUserId) &&
			secAppRole == SecAppRole.load(secAppRoleId)
		}.count() > 0
	}

	static SecAppUserSecAppRole create(SecAppUser secAppUser, SecAppRole secAppRole, boolean flush = false) {
		def instance = new SecAppUserSecAppRole(secAppUser: secAppUser, secAppRole: secAppRole)
		instance.save(flush: flush, insert: true)
		instance
	}

	static boolean remove(SecAppUser u, SecAppRole r, boolean flush = false) {
		if (u == null || r == null) return false

		int rowCount = SecAppUserSecAppRole.where {
			secAppUser == SecAppUser.load(u.id) &&
			secAppRole == SecAppRole.load(r.id)
		}.deleteAll()

		if (flush) { SecAppUserSecAppRole.withSession { it.flush() } }

		rowCount > 0
	}

	static void removeAll(SecAppUser u, boolean flush = false) {
		if (u == null) return

		SecAppUserSecAppRole.where {
			secAppUser == SecAppUser.load(u.id)
		}.deleteAll()

		if (flush) { SecAppUserSecAppRole.withSession { it.flush() } }
	}

	static void removeAll(SecAppRole r, boolean flush = false) {
		if (r == null) return

		SecAppUserSecAppRole.where {
			secAppRole == SecAppRole.load(r.id)
		}.deleteAll()

		if (flush) { SecAppUserSecAppRole.withSession { it.flush() } }
	}

	static constraints = {
		secAppRole validator: { SecAppRole r, SecAppUserSecAppRole ur ->
			if (ur.secAppUser == null) return
			boolean existing = false
			SecAppUserSecAppRole.withNewSession {
				existing = SecAppUserSecAppRole.exists(ur.secAppUser.id, r.id)
			}
			if (existing) {
				return 'userRole.exists'
			}
		}
	}

	static mapping = {
		id composite: ['secAppRole', 'secAppUser']
		version false
	}
}

grails-app/controllers/com/kathsoftware/SecAppUserSecAppRoleController.groovy
package com.kathsoftware



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SecAppUserSecAppRoleController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond SecAppUserSecAppRole.list(params), model:[secAppUserSecAppRoleInstanceCount: SecAppUserSecAppRole.count()]
    }

    def show(SecAppUserSecAppRole secAppUserSecAppRoleInstance) {
        respond secAppUserSecAppRoleInstance
    }

    def create() {
        respond new SecAppUserSecAppRole(params)
    }

    @Transactional
    def save(SecAppUserSecAppRole secAppUserSecAppRoleInstance) {
        if (secAppUserSecAppRoleInstance == null) {
            notFound()
            return
        }

        if (secAppUserSecAppRoleInstance.hasErrors()) {
            respond secAppUserSecAppRoleInstance.errors, view:'create'
            return
        }

        secAppUserSecAppRoleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'secAppUserSecAppRole.label', default: 'SecAppUserSecAppRole'), secAppUserSecAppRoleInstance.id])
                redirect secAppUserSecAppRoleInstance
            }
            '*' { respond secAppUserSecAppRoleInstance, [status: CREATED] }
        }
    }

    def edit(SecAppUserSecAppRole secAppUserSecAppRoleInstance) {
        respond secAppUserSecAppRoleInstance
    }

    @Transactional
    def update(SecAppUserSecAppRole secAppUserSecAppRoleInstance) {
        if (secAppUserSecAppRoleInstance == null) {
            notFound()
            return
        }

        if (secAppUserSecAppRoleInstance.hasErrors()) {
            respond secAppUserSecAppRoleInstance.errors, view:'edit'
            return
        }

        secAppUserSecAppRoleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'SecAppUserSecAppRole.label', default: 'SecAppUserSecAppRole'), secAppUserSecAppRoleInstance.id])
                redirect secAppUserSecAppRoleInstance
            }
            '*'{ respond secAppUserSecAppRoleInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(SecAppUserSecAppRole secAppUserSecAppRoleInstance) {

        if (secAppUserSecAppRoleInstance == null) {
            notFound()
            return
        }

        secAppUserSecAppRoleInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'SecAppUserSecAppRole.label', default: 'SecAppUserSecAppRole'), secAppUserSecAppRoleInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'secAppUserSecAppRole.label', default: 'SecAppUserSecAppRole'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/secAppUserSecAppRole/_form.gsp
<%@ page import="com.kathsoftware.SecAppUserSecAppRole" %>



<div class="fieldcontain ${hasErrors(bean: secAppUserSecAppRoleInstance, field: 'secAppRole', 'error')} required">
	<label for="secAppRole">
		<g:message code="secAppUserSecAppRole.secAppRole.label" default="Sec App Role" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="secAppRole" name="secAppRole.id" from="${com.kathsoftware.SecAppRole.list()}" optionKey="id" required="" value="${secAppUserSecAppRoleInstance?.secAppRole?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: secAppUserSecAppRoleInstance, field: 'secAppUser', 'error')} required">
	<label for="secAppUser">
		<g:message code="secAppUserSecAppRole.secAppUser.label" default="Sec App User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="secAppUser" name="secAppUser.id" from="${com.kathsoftware.SecAppUser.list()}" optionKey="id" required="" value="${secAppUserSecAppRoleInstance?.secAppUser?.id}" class="many-to-one"/>

</div>

grails-app/views/secAppUserSecAppRole/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUserSecAppRole.label', default: 'SecAppUserSecAppRole')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-secAppUserSecAppRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-secAppUserSecAppRole" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${secAppUserSecAppRoleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${secAppUserSecAppRoleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:secAppUserSecAppRoleInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/secAppUserSecAppRole/edit.gsp
<%@ page import="com.kathsoftware.SecAppUserSecAppRole" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUserSecAppRole.label', default: 'SecAppUserSecAppRole')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-secAppUserSecAppRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-secAppUserSecAppRole" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${secAppUserSecAppRoleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${secAppUserSecAppRoleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:secAppUserSecAppRoleInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${secAppUserSecAppRoleInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/secAppUserSecAppRole/index.gsp
<%@ page import="com.kathsoftware.SecAppUserSecAppRole" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUserSecAppRole.label', default: 'SecAppUserSecAppRole')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-secAppUserSecAppRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-secAppUserSecAppRole" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="secAppUserSecAppRole.secAppRole.label" default="Sec App Role" /></th>
					
						<th><g:message code="secAppUserSecAppRole.secAppUser.label" default="Sec App User" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${secAppUserSecAppRoleInstanceList}" status="i" var="secAppUserSecAppRoleInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${secAppUserSecAppRoleInstance.id}">${fieldValue(bean: secAppUserSecAppRoleInstance, field: "secAppRole")}</g:link></td>
					
						<td>${fieldValue(bean: secAppUserSecAppRoleInstance, field: "secAppUser")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${secAppUserSecAppRoleInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/secAppUserSecAppRole/show.gsp
<%@ page import="com.kathsoftware.SecAppUserSecAppRole" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'secAppUserSecAppRole.label', default: 'SecAppUserSecAppRole')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-secAppUserSecAppRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-secAppUserSecAppRole" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list secAppUserSecAppRole">
			
				<g:if test="${secAppUserSecAppRoleInstance?.secAppRole}">
				<li class="fieldcontain">
					<span id="secAppRole-label" class="property-label"><g:message code="secAppUserSecAppRole.secAppRole.label" default="Sec App Role" /></span>
					
						<span class="property-value" aria-labelledby="secAppRole-label"><g:link controller="secAppRole" action="show" id="${secAppUserSecAppRoleInstance?.secAppRole?.id}">${secAppUserSecAppRoleInstance?.secAppRole?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${secAppUserSecAppRoleInstance?.secAppUser}">
				<li class="fieldcontain">
					<span id="secAppUser-label" class="property-label"><g:message code="secAppUserSecAppRole.secAppUser.label" default="Sec App User" /></span>
					
						<span class="property-value" aria-labelledby="secAppUser-label"><g:link controller="secAppUser" action="show" id="${secAppUserSecAppRoleInstance?.secAppUser?.id}">${secAppUserSecAppRoleInstance?.secAppUser?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:secAppUserSecAppRoleInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${secAppUserSecAppRoleInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>