grails-app/domain/com/kathsoftware/ChatMessage.groovy
package com.kathsoftware

class ChatMessage {

	String fromUser
	String toUser
	String message
	Date dateTimeSent
	
    static constraints = {
    }
}

grails-app/controllers/com/kathsoftware/ChatMessageController.groovy
package com.kathsoftware

import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured
import java.util.Date;


class ChatMessageController {

	def blueChatLoggingService
		
	def springSecurityService
	
	@Secured(['IS_AUTHENTICATED_FULLY'])
    def index() { }
	
	@Secured(['IS_AUTHENTICATED_FULLY'])
	def getUserList() {

		def currentUser = SecAppUser.findById(springSecurityService.currentUser.id).username
		
		blueChatLoggingService.logDebugMessage("Getting User List For User: " + currentUser)
		
		def results = SecAppUser.findAll(sort:"username", order: "asc"){
			username != currentUser			
		}

		blueChatLoggingService.logDebugMessage("getUserList(): Returning " + results.size() + " users.")
						
		JSON.use('deep')
		render results as JSON
	}
	
	@Secured(['IS_AUTHENTICATED_FULLY'])
	def sendMessage(String message, String user){
		
		ChatMessage msg = new ChatMessage()
		
		msg.fromUser = SecAppUser.findById(springSecurityService.currentUser.id).username
		msg.toUser = user
		msg.message = message
		msg.dateTimeSent = new Date()

		blueChatLoggingService.logDebugMessage("Sending Message '" + msg.message + 
											"' From User '" + msg.fromUser + "' To User: '" + msg.toUser + "'")				
		String returnMessage = "Message Sent!"
		
		if (!msg.save(flush: true)) {
			blueChatLoggingService.logDebugMessage("Error Saving Message: ")
			msg.errors.each {
				blueChatLoggingService.logDebugMessage("Error: " + it)
			}
			
			returnMessage = "Error Sending Message"
		}
		
		render returnMessage
	}
	
	@Secured(['IS_AUTHENTICATED_FULLY'])
	def getMessages(String username){		
		
		String fromUserStr = SecAppUser.findById(springSecurityService.currentUser.id).username
		
		blueChatLoggingService.logDebugMessage("Returning Messages For User: " + username)
		
		
		def results = ChatMessage.where {
			(fromUser == fromUserStr && toUser == username) || (fromUser == username && toUser == fromUserStr)
		}.list()
		
		blueChatLoggingService.logDebugMessage("getMessages():Returning " + results.size() + " users.")
			
		def msgList = []
		for(result in results){
			def dt = result.dateTimeSent.format("MM/dd/yyyy HH:mm:ss")
			def map = [dateTimeSent:dt, fromUser:result.fromUser, toUser:result.toUser, message:result.message]
			msgList.add(map)
		}
		
		JSON.use('deep')
		render msgList as JSON
	}
		
}

grails-app/views/chatMessage/_form.gsp
<%@ page import="com.kathsoftware.ChatMessage" %>



<div class="fieldcontain ${hasErrors(bean: chatMessageInstance, field: 'dateTimeSent', 'error')} required">
	<label for="dateTimeSent">
		<g:message code="chatMessage.dateTimeSent.label" default="Date Time Sent" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="dateTimeSent" precision="day"  value="${chatMessageInstance?.dateTimeSent}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: chatMessageInstance, field: 'fromUser', 'error')} required">
	<label for="fromUser">
		<g:message code="chatMessage.fromUser.label" default="From User" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="fromUser" required="" value="${chatMessageInstance?.fromUser}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chatMessageInstance, field: 'message', 'error')} required">
	<label for="message">
		<g:message code="chatMessage.message.label" default="Message" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="message" required="" value="${chatMessageInstance?.message}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chatMessageInstance, field: 'toUser', 'error')} required">
	<label for="toUser">
		<g:message code="chatMessage.toUser.label" default="To User" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="toUser" required="" value="${chatMessageInstance?.toUser}"/>

</div>

grails-app/views/chatMessage/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'chatMessage.label', default: 'ChatMessage')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-chatMessage" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-chatMessage" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${chatMessageInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${chatMessageInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:chatMessageInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/chatMessage/edit.gsp
<%@ page import="com.kathsoftware.ChatMessage" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'chatMessage.label', default: 'ChatMessage')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-chatMessage" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-chatMessage" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${chatMessageInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${chatMessageInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:chatMessageInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${chatMessageInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/chatMessage/index.gsp
<%@ page import="com.kathsoftware.ChatMessage" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title>Blue Chat</title>
		
		<script type='text/javascript' src='js/jquery-2.1.3.js'></script>

<script type='text/javascript'>

var sendToUser = "";
setInterval(function () {getUsers()}, 5000);
setInterval(function () {getMessages()}, 10000);

function getUsers()
{
    $.ajax({
      url: 'ChatMessage/getUserList/',
      data: 'username=' + "jkath", 
      dataType: 'json', // Choosing a JSON datatype
      success: function(data)
      {
	    var $select = $('#userselectlist');                        
		$select.find('option').remove();
		
        for (var x = 0; x < data.length; x++) {
	    	$select.append("<option value='username'>" + data[x].username + '</option>');
        }      	
        
        if(sendToUser != ""){
        	$("#userselectlist option").filter(function() {
    			return $(this).text() == sendToUser; 
			}).prop('selected', true);
        }
        
      }
    });
    
}

function getMessages()
{
    $.ajax({ 
      url: 'ChatMessage/getMessages/',
      data: 'username=' + sendToUser, 
      dataType: 'json',
      success: function(data) 
      {
      
      	var $messages = $('#messageslistarea');
      
	    $messages.val("");
		
		for (i = 0; i < data.length; i++) {

            var dt = data[i].dateTimeSent;
            var fromUser = data[i].fromUser;
            var toUser = data[i].toUser;
            var msg = data[i].message;

            $messages.val( $messages.val() + "\n" + dt + "    From: " + fromUser + "    To: " + toUser );
            
            $messages.val( $messages.val() + "\n" + msg + "\n");
            
            $messages.scrollTop($('#messageslistarea')[0].scrollHeight);

        }
        
      }
    });
    
    $("#responsemessage").text("");
    
}

function postMessage()
{
	$("#responsemessage").text("");

	$("#userselectlist option:selected").text();

	var $messageTA = $('#sendmessage');
	
	$.ajax({ // ajax call starts
      url: 'ChatMessage/sendMessage/',
      data: 'message=' + $messageTA.val() + "&" + "user=" + sendToUser, 
      success: function(data)
      {
		$("#responsemessage").text(data);
		$messageTA.val("");
		getMessages();
      }
    });
}

$(document).ready(function(){
	
	$("#sendtomessagelabel").text("Recipient: None Selected Yet");
	$("#messagesfromuser").text("Recipient Not Selected Yet");
	
	
	
	$("#sendmessagebtn").prop("disabled", true);
	
	$("#userselectlist").on('change', function (e) {
	    var optionSelected = $(this).find("option:selected");
     	sendToUser = optionSelected.text();
		$("#sendtomessagelabel").text("Recipient: " + sendToUser);     	
		$("#sendmessagebtn").prop("disabled", false);
		$("#messagesfromuser").text(sendToUser);     
		getMessages();	
	});
	
	$( "#sendmessagebtn" ).click(function() {
	  postMessage();
	});
	
	getUsers();
	getMessages();
	
	$("#messageslistarea").prop("disabled", true);
});

</script>	

		<style type="text/css">
			body {color: white; background-image: url(assets/bluebgtile.jpg);}
		</style>
		

	</head>
	<body>

		<div id="messagelist" style="margin-left: 20px;">
			Conversations With: <span id="messagesfromuser"></span>
			<textarea id="messageslistarea" style="height: 400px; width: 850px"></textarea>
		</div>	
	
		<div id="userlist" style="float: left;  margin-left: 20px;">
			<br>Users<br>
			<select id="userselectlist" size="5" style="min-width:100px;">
			</select>
		</div>	
		
		<div id="sendmessagearea" style="float: left; margin-left: 20px;">
			<br>
			<span id="sendtomessagelabel"></span>
			<br>
			<textarea id="sendmessage" style="height: 100px; width: 730px;"></textarea>
			<br>
			<button id="sendmessagebtn">Send Message</button>
			<br><br>
			<span id="responsemessage"></span>
		</div>	

		
	</body>
</html>

grails-app/views/chatMessage/show.gsp
<%@ page import="com.kathsoftware.ChatMessage" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'chatMessage.label', default: 'ChatMessage')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-chatMessage" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-chatMessage" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list chatMessage">
			
				<g:if test="${chatMessageInstance?.dateTimeSent}">
				<li class="fieldcontain">
					<span id="dateTimeSent-label" class="property-label"><g:message code="chatMessage.dateTimeSent.label" default="Date Time Sent" /></span>
					
						<span class="property-value" aria-labelledby="dateTimeSent-label"><g:formatDate date="${chatMessageInstance?.dateTimeSent}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${chatMessageInstance?.fromUser}">
				<li class="fieldcontain">
					<span id="fromUser-label" class="property-label"><g:message code="chatMessage.fromUser.label" default="From User" /></span>
					
						<span class="property-value" aria-labelledby="fromUser-label"><g:fieldValue bean="${chatMessageInstance}" field="fromUser"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${chatMessageInstance?.message}">
				<li class="fieldcontain">
					<span id="message-label" class="property-label"><g:message code="chatMessage.message.label" default="Message" /></span>
					
						<span class="property-value" aria-labelledby="message-label"><g:fieldValue bean="${chatMessageInstance}" field="message"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${chatMessageInstance?.toUser}">
				<li class="fieldcontain">
					<span id="toUser-label" class="property-label"><g:message code="chatMessage.toUser.label" default="To User" /></span>
					
						<span class="property-value" aria-labelledby="toUser-label"><g:fieldValue bean="${chatMessageInstance}" field="toUser"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:chatMessageInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${chatMessageInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>